In [48]:
from __future__ import print_function, absolute_import
from gm.api import *
from gm.model.storage import context
from gm.model import DictLikeAlgoOrder
from gm.pb.account_pb2 import AlgoOrder
import numpy as np
import pandas as pd
from datetime import  datetime,timezone, timedelta
import datetime
import copy
import plotly.express as px
import plotly.graph_objects as go
pd.set_option('display.max_rows', None) #show all rows
pd.set_option('display.float_format', '{:.2f}'.format)
import warnings
warnings.filterwarnings('ignore')

#掘金量化
set_token('807b8ba88782d7343bfe3ad918f33f93a2610ee8')
account_id='28edb8c3-ed6d-11f0-9ac0-00163e022aa6'

In [ ]:
#KDJ
stock='SHSE.601606'
start='2025-08-25'
end='2026-02-13'
n=9

In [50]:
history_data = history(symbol=stock, frequency='1d', start_time=start,  end_time=end, fields='close,eob', adjust=ADJUST_PREV, df= True)
history_data['eob'] = history_data['eob'].dt.date  #优化日期格式

In [ ]:
history_data['max_9']=[50]*len(history_data)
history_data['min_9']=[50]*len(history_data)

for i in range(8,len(history_data)):
    max_i=max(history_data['close'][i-8:i+1])
    min_i=min(history_data['close'][i-8:i+1])

    history_data['max_9'][i]=max_i
    history_data['min_9'][i]=min_i
history_data

     close         eob  max_9  min_9
0    62.14  2025-08-25  50.00  50.00
1    65.45  2025-08-26  50.00  50.00
2    63.27  2025-08-27  50.00  50.00
3    62.88  2025-08-28  50.00  50.00
4    69.17  2025-08-29  50.00  50.00
5    70.70  2025-09-01  50.00  50.00
6    72.42  2025-09-02  50.00  50.00
7    65.18  2025-09-03  50.00  50.00
8    58.66  2025-09-04  72.42  58.66
9    53.55  2025-09-05  72.42  53.55
10   48.24  2025-09-08  72.42  48.24
11   47.39  2025-09-09  72.42  47.39
12   46.27  2025-09-10  72.42  46.27
13   47.12  2025-09-11  72.42  46.27
14   49.95  2025-09-12  72.42  46.27
15   49.17  2025-09-15  65.18  46.27
16   47.76  2025-09-16  58.66  46.27
17   47.07  2025-09-17  53.55  46.27
18   46.49  2025-09-18  49.95  46.27
19   46.91  2025-09-19  49.95  46.27
20   46.62  2025-09-22  49.95  46.27
21   44.65  2025-09-23  49.95  44.65
22   44.07  2025-09-24  49.95  44.07
23   42.84  2025-09-25  49.17  42.84
24   42.44  2025-09-26  47.76  42.44
25   41.93  2025-09-29  47.07  41.93
26   42.68  2025-09-30  46.91  41.93
27   42.91  2025-10-09  46.91  41.93
28   47.20  2025-10-10  47.20  41.93
29   51.92  2025-10-13  51.92  41.93
30   56.00  2025-10-14  56.00  41.93
31   51.88  2025-10-15  56.00  41.93
32   53.10  2025-10-16  56.00  41.93
33   49.57  2025-10-17  56.00  41.93
34   48.31  2025-10-20  56.00  42.68
35   48.88  2025-10-21  56.00  42.91
36   48.05  2025-10-22  56.00  47.20
37   48.95  2025-10-23  56.00  48.05
38   51.27  2025-10-24  56.00  48.05
39   49.98  2025-10-27  53.10  48.05
40   54.98  2025-10-28  54.98  48.05
41   55.47  2025-10-29  55.47  48.05
42   51.82  2025-10-30  55.47  48.05
43   51.26  2025-10-31  55.47  48.05
44   51.31  2025-11-03  55.47  48.05
45   52.51  2025-11-04  55.47  48.95
46   50.44  2025-11-05  55.47  49.98
47   50.52  2025-11-06  55.47  49.98
48   48.80  2025-11-07  55.47  48.80
49   48.19  2025-11-10  55.47  48.19
50   48.43  2025-11-11  52.51  48.19
51   46.07  2025-11-12  52.51  46.07
52   46.42  2025-11-13  52.51  46.07
53   48.68  2025-11-14  52.51  46.07
54   53.55  2025-11-17  53.55  46.07
55   52.22  2025-11-18  53.55  46.07
56   55.15  2025-11-19  55.15  46.07
57   52.00  2025-11-20  55.15  46.07
58   52.21  2025-11-21  55.15  46.07
59   57.43  2025-11-24  57.43  46.07
60   57.30  2025-11-25  57.43  46.42
61   52.69  2025-11-26  57.43  48.68
62   52.10  2025-11-27  57.43  52.00
63   52.95  2025-11-28  57.43  52.00
64   52.22  2025-12-01  57.43  52.00
65   52.49  2025-12-02  57.43  52.00
66   50.03  2025-12-03  57.43  50.03
67   49.34  2025-12-04  57.43  49.34
68   49.86  2025-12-05  57.30  49.34
69   50.17  2025-12-08  52.95  49.34
70   49.19  2025-12-09  52.95  49.19
71   49.24  2025-12-10  52.95  49.19
72   48.51  2025-12-11  52.49  48.51
73   48.43  2025-12-12  52.49  48.43
74   47.51  2025-12-15  50.17  47.51
75   46.11  2025-12-16  50.17  46.11
76   47.10  2025-12-17  50.17  46.11
77   48.93  2025-12-18  50.17  46.11
78   48.11  2025-12-19  49.24  46.11
79   47.83  2025-12-22  49.24  46.11
80   47.08  2025-12-23  48.93  46.11
81   47.64  2025-12-24  48.93  46.11
82   48.00  2025-12-25  48.93  46.11
83   47.94  2025-12-26  48.93  46.11
84   48.39  2025-12-29  48.93  47.08
85   50.26  2025-12-30  50.26  47.08
86   48.12  2025-12-31  50.26  47.08
87   49.46  2026-01-05  50.26  47.08
88   49.29  2026-01-06  50.26  47.08
89   48.56  2026-01-07  50.26  47.64
90   49.74  2026-01-08  50.26  47.94
91   51.97  2026-01-09  51.97  47.94
92   51.28  2026-01-12  51.97  48.12
93   49.02  2026-01-13  51.97  48.12
94   48.90  2026-01-14  51.97  48.12
95   49.14  2026-01-15  51.97  48.56
96   48.28  2026-01-16  51.97  48.28
97   48.42  2026-01-19  51.97  48.28
98   47.22  2026-01-20  51.97  47.22
99   47.31  2026-01-21  51.97  47.22
100  47.45  2026-01-22  51.28  47.22
101  47.69  2026-01-23  49.14  47.22
102  46.90  2026-01-26  49.14  46.90
103  47.14  2026-01-27  49.14  46.90
104  46.22  2026-01-28  48.42  46.22
105  45.36  2026-01-29  48.42  45.36
106  45.71  2026-01-30  47.69  45.36
107  44.01  2026-02-02  47.69  44.01
108  44.49  2026-02-03  47.69  44.01
109  44.77  2026-02-04  47.69  44.01
110  44.06  2026-02-05  47.14  44.01
111  44.08  2026-02-06  47.14  44.01
112  44.71  2026-02-09  46.22  44.01
113  44.94  2026-02-10  45.71  44.01
114  44.82  2026-02-11  45.71  44.01
115  44.38  2026-02-12  44.94  44.01
116  44.83  2026-02-13  44.94  44.06

In [52]:
history_data['rsv']=[0]*len(history_data)
for i in range(8,len(history_data)):
    history_data['rsv'][i]=((history_data['close'][i]-history_data['min_9'][i]) /(history_data['max_9'][i]-history_data['min_9'][i])) * 100
history_data

     close         eob  max_9  min_9    rsv
0    62.14  2025-08-25  50.00  50.00   0.00
1    65.45  2025-08-26  50.00  50.00   0.00
2    63.27  2025-08-27  50.00  50.00   0.00
3    62.88  2025-08-28  50.00  50.00   0.00
4    69.17  2025-08-29  50.00  50.00   0.00
5    70.70  2025-09-01  50.00  50.00   0.00
6    72.42  2025-09-02  50.00  50.00   0.00
7    65.18  2025-09-03  50.00  50.00   0.00
8    58.66  2025-09-04  72.42  58.66   0.00
9    53.55  2025-09-05  72.42  53.55   0.00
10   48.24  2025-09-08  72.42  48.24   0.00
11   47.39  2025-09-09  72.42  47.39   0.00
12   46.27  2025-09-10  72.42  46.27   0.00
13   47.12  2025-09-11  72.42  46.27   3.25
14   49.95  2025-09-12  72.42  46.27  14.07
15   49.17  2025-09-15  65.18  46.27  15.34
16   47.76  2025-09-16  58.66  46.27  12.03
17   47.07  2025-09-17  53.55  46.27  10.99
18   46.49  2025-09-18  49.95  46.27   5.98
19   46.91  2025-09-19  49.95  46.27  17.39
20   46.62  2025-09-22  49.95  46.27   9.51
21   44.65  2025-09-23  49.95  44.65   0.00
22   44.07  2025-09-24  49.95  44.07   0.00
23   42.84  2025-09-25  49.17  42.84   0.00
24   42.44  2025-09-26  47.76  42.44   0.00
25   41.93  2025-09-29  47.07  41.93   0.00
26   42.68  2025-09-30  46.91  41.93  15.06
27   42.91  2025-10-09  46.91  41.93  19.68
28   47.20  2025-10-10  47.20  41.93 100.00
29   51.92  2025-10-13  51.92  41.93 100.00
30   56.00  2025-10-14  56.00  41.93 100.00
31   51.88  2025-10-15  56.00  41.93  70.72
32   53.10  2025-10-16  56.00  41.93  79.39
33   49.57  2025-10-17  56.00  41.93  54.30
34   48.31  2025-10-20  56.00  42.68  42.27
35   48.88  2025-10-21  56.00  42.91  45.61
36   48.05  2025-10-22  56.00  47.20   9.66
37   48.95  2025-10-23  56.00  48.05  11.32
38   51.27  2025-10-24  56.00  48.05  40.50
39   49.98  2025-10-27  53.10  48.05  38.22
40   54.98  2025-10-28  54.98  48.05 100.00
41   55.47  2025-10-29  55.47  48.05 100.00
42   51.82  2025-10-30  55.47  48.05  50.81
43   51.26  2025-10-31  55.47  48.05  43.26
44   51.31  2025-11-03  55.47  48.05  43.94
45   52.51  2025-11-04  55.47  48.95  54.60
46   50.44  2025-11-05  55.47  49.98   8.38
47   50.52  2025-11-06  55.47  49.98   9.84
48   48.80  2025-11-07  55.47  48.80   0.00
49   48.19  2025-11-10  55.47  48.19   0.00
50   48.43  2025-11-11  52.51  48.19   5.56
51   46.07  2025-11-12  52.51  46.07   0.00
52   46.42  2025-11-13  52.51  46.07   5.43
53   48.68  2025-11-14  52.51  46.07  40.53
54   53.55  2025-11-17  53.55  46.07 100.00
55   52.22  2025-11-18  53.55  46.07  82.22
56   55.15  2025-11-19  55.15  46.07 100.00
57   52.00  2025-11-20  55.15  46.07  65.31
58   52.21  2025-11-21  55.15  46.07  67.62
59   57.43  2025-11-24  57.43  46.07 100.00
60   57.30  2025-11-25  57.43  46.42  98.82
61   52.69  2025-11-26  57.43  48.68  45.83
62   52.10  2025-11-27  57.43  52.00   1.84
63   52.95  2025-11-28  57.43  52.00  17.50
64   52.22  2025-12-01  57.43  52.00   4.05
65   52.49  2025-12-02  57.43  52.00   9.02
66   50.03  2025-12-03  57.43  50.03   0.00
67   49.34  2025-12-04  57.43  49.34   0.00
68   49.86  2025-12-05  57.30  49.34   6.53
69   50.17  2025-12-08  52.95  49.34  22.99
70   49.19  2025-12-09  52.95  49.19   0.00
71   49.24  2025-12-10  52.95  49.19   1.33
72   48.51  2025-12-11  52.49  48.51   0.00
73   48.43  2025-12-12  52.49  48.43   0.00
74   47.51  2025-12-15  50.17  47.51   0.00
75   46.11  2025-12-16  50.17  46.11   0.00
76   47.10  2025-12-17  50.17  46.11  24.38
77   48.93  2025-12-18  50.17  46.11  69.46
78   48.11  2025-12-19  49.24  46.11  63.90
79   47.83  2025-12-22  49.24  46.11  54.95
80   47.08  2025-12-23  48.93  46.11  34.40
81   47.64  2025-12-24  48.93  46.11  54.26
82   48.00  2025-12-25  48.93  46.11  67.02
83   47.94  2025-12-26  48.93  46.11  64.89
84   48.39  2025-12-29  48.93  47.08  70.81
85   50.26  2025-12-30  50.26  47.08 100.00
86   48.12  2025-12-31  50.26  47.08  32.70
87   49.46  2026-01-05  50.26  47.08  74.84
88   49.29  2026-01-06  50.26  47.08  69.50
89   48.56  2026-01-07  50.26  47.64  35.11
90   49.74  2026-01-08  50.26  47.94  77.59
91   51.97  2026-01-09  51.97  47.94 100.00
92   51.28  2026-01-12  51.97  48.12  82.08
93   49.02  2026-01-13  51.97  48.12  23.38
94   48.90  2026-01-14  51.97  48.12  20.26
95   49.14  2026-01-15  51.97  48.56  17.01
96   48.28  2026-01-16  51.97  48.28   0.00
97   48.42  2026-01-19  51.97  48.28   3.79
98   47.22  2026-01-20  51.97  47.22   0.00
99   47.31  2026-01-21  51.97  47.22   1.89
100  47.45  2026-01-22  51.28  47.22   5.67
101  47.69  2026-01-23  49.14  47.22  24.48
102  46.90  2026-01-26  49.14  46.90   0.00
103  47.14  2026-01-27  49.14  46.90  10.71
104  46.22  2026-01-28  48.42  46.22   0.00
105  45.36  2026-01-29  48.42  45.36   0.00
106  45.71  2026-01-30  47.69  45.36  15.02
107  44.01  2026-02-02  47.69  44.01   0.00
108  44.49  2026-02-03  47.69  44.01  13.04
109  44.77  2026-02-04  47.69  44.01  20.65
110  44.06  2026-02-05  47.14  44.01   1.60
111  44.08  2026-02-06  47.14  44.01   2.24
112  44.71  2026-02-09  46.22  44.01  31.67
113  44.94  2026-02-10  45.71  44.01  54.71
114  44.82  2026-02-11  45.71  44.01  47.65
115  44.38  2026-02-12  44.94  44.01  39.78
116  44.83  2026-02-13  44.94  44.06  87.50

In [53]:
history_data['k']=[0]*len(history_data)
for i in range(9,len(history_data)):
    history_data['k'][i]=(1/3)*history_data['rsv'][i] + (2/3)*history_data['k'][i-1]
history_data['d']=[0]*len(history_data)
for i in range(9,len(history_data)):
    history_data['d'][i]=(1/3)*history_data['k'][i] + (2/3)*history_data['d'][i-1]
history_data['j']=[0]*len(history_data)
for i in range(9,len(history_data)):
    history_data['j'][i]=3*history_data['k'][i] - 2*history_data['d'][i]
history_data

     close         eob  max_9  min_9    rsv     k     d      j
0    62.14  2025-08-25  50.00  50.00   0.00  0.00  0.00   0.00
1    65.45  2025-08-26  50.00  50.00   0.00  0.00  0.00   0.00
2    63.27  2025-08-27  50.00  50.00   0.00  0.00  0.00   0.00
3    62.88  2025-08-28  50.00  50.00   0.00  0.00  0.00   0.00
4    69.17  2025-08-29  50.00  50.00   0.00  0.00  0.00   0.00
5    70.70  2025-09-01  50.00  50.00   0.00  0.00  0.00   0.00
6    72.42  2025-09-02  50.00  50.00   0.00  0.00  0.00   0.00
7    65.18  2025-09-03  50.00  50.00   0.00  0.00  0.00   0.00
8    58.66  2025-09-04  72.42  58.66   0.00  0.00  0.00   0.00
9    53.55  2025-09-05  72.42  53.55   0.00  0.00  0.00   0.00
10   48.24  2025-09-08  72.42  48.24   0.00  0.00  0.00   0.00
11   47.39  2025-09-09  72.42  47.39   0.00  0.00  0.00   0.00
12   46.27  2025-09-10  72.42  46.27   0.00  0.00  0.00   0.00
13   47.12  2025-09-11  72.42  46.27   3.25  1.08  0.36   2.53
14   49.95  2025-09-12  72.42  46.27  14.07  5.41  2.05  12.15
15   49.17  2025-09-15  65.18  46.27  15.34  8.72  4.27  17.62
16   47.76  2025-09-16  58.66  46.27  12.03  9.82  6.12  17.23
17   47.07  2025-09-17  53.55  46.27  10.99 10.21  7.48  15.66
18   46.49  2025-09-18  49.95  46.27   5.98  8.80  7.92  10.55
19   46.91  2025-09-19  49.95  46.27  17.39 11.66  9.17  16.65
20   46.62  2025-09-22  49.95  46.27   9.51 10.95  9.76  13.31
21   44.65  2025-09-23  49.95  44.65   0.00  7.30  8.94   4.01
22   44.07  2025-09-24  49.95  44.07   0.00  4.87  7.58  -0.57
23   42.84  2025-09-25  49.17  42.84   0.00  3.24  6.14  -2.54
24   42.44  2025-09-26  47.76  42.44   0.00  2.16  4.81  -3.14
25   41.93  2025-09-29  47.07  41.93   0.00  1.44  3.69  -3.05
26   42.68  2025-09-30  46.91  41.93  15.06  5.98  4.45   9.04
27   42.91  2025-10-09  46.91  41.93  19.68 10.55  6.48  18.67
28   47.20  2025-10-10  47.20  41.93 100.00 40.36 17.78  85.54
29   51.92  2025-10-13  51.92  41.93 100.00 60.24 31.93 116.86
30   56.00  2025-10-14  56.00  41.93 100.00 73.50 45.79 128.91
31   51.88  2025-10-15  56.00  41.93  70.72 72.57 54.71 108.28
32   53.10  2025-10-16  56.00  41.93  79.39 74.84 61.42 101.68
33   49.57  2025-10-17  56.00  41.93  54.30 68.00 63.61  76.76
34   48.31  2025-10-20  56.00  42.68  42.27 59.42 62.22  53.83
35   48.88  2025-10-21  56.00  42.91  45.61 54.82 59.75  44.95
36   48.05  2025-10-22  56.00  47.20   9.66 39.76 53.09  13.12
37   48.95  2025-10-23  56.00  48.05  11.32 30.28 45.49  -0.12
38   51.27  2025-10-24  56.00  48.05  40.50 33.69 41.55  17.96
39   49.98  2025-10-27  53.10  48.05  38.22 35.20 39.44  26.73
40   54.98  2025-10-28  54.98  48.05 100.00 56.80 45.22  79.95
41   55.47  2025-10-29  55.47  48.05 100.00 71.20 53.88 105.83
42   51.82  2025-10-30  55.47  48.05  50.81 64.40 57.39  78.43
43   51.26  2025-10-31  55.47  48.05  43.26 57.36 57.38  57.31
44   51.31  2025-11-03  55.47  48.05  43.94 52.88 55.88  46.89
45   52.51  2025-11-04  55.47  48.95  54.60 53.46 55.07  50.22
46   50.44  2025-11-05  55.47  49.98   8.38 38.43 49.52  16.24
47   50.52  2025-11-06  55.47  49.98   9.84 28.90 42.65   1.40
48   48.80  2025-11-07  55.47  48.80   0.00 19.27 34.85 -11.91
49   48.19  2025-11-10  55.47  48.19   0.00 12.84 27.52 -16.50
50   48.43  2025-11-11  52.51  48.19   5.56 10.41 21.82 -12.39
51   46.07  2025-11-12  52.51  46.07   0.00  6.94 16.86 -12.89
52   46.42  2025-11-13  52.51  46.07   5.43  6.44 13.39  -7.45
53   48.68  2025-11-14  52.51  46.07  40.53 17.80 14.86  23.69
54   53.55  2025-11-17  53.55  46.07 100.00 45.20 24.97  85.66
55   52.22  2025-11-18  53.55  46.07  82.22 57.54 35.83 100.97
56   55.15  2025-11-19  55.15  46.07 100.00 71.69 47.78 119.51
57   52.00  2025-11-20  55.15  46.07  65.31 69.57 55.04  98.61
58   52.21  2025-11-21  55.15  46.07  67.62 68.92 59.67  87.41
59   57.43  2025-11-24  57.43  46.07 100.00 79.28 66.21 105.42
60   57.30  2025-11-25  57.43  46.42  98.82 85.79 72.73 111.91
61   52.69  2025-11-26  57.43  48.68  45.83 72.47 72.65  72.12
62   52.10  2025-11-27  57.43  52.00   1.84 48.93 64.74  17.30
63   52.95  2025-11-28  57.43  52.00  17.50 38.45 55.98   3.40
64   52.22  2025-12-01  57.43  52.00   4.05 26.98 46.31 -11.67
65   52.49  2025-12-02  57.43  52.00   9.02 21.00 37.87 -12.76
66   50.03  2025-12-03  57.43  50.03   0.00 14.00 29.92 -17.84
67   49.34  2025-12-04  57.43  49.34   0.00  9.33 23.05 -18.11
68   49.86  2025-12-05  57.30  49.34   6.53  8.40 18.17 -11.14
69   50.17  2025-12-08  52.95  49.34  22.99 13.26 16.53   6.72
70   49.19  2025-12-09  52.95  49.19   0.00  8.84 13.97  -1.41
71   49.24  2025-12-10  52.95  49.19   1.33  6.34 11.43  -3.84
72   48.51  2025-12-11  52.49  48.51   0.00  4.23  9.03  -5.38
73   48.43  2025-12-12  52.49  48.43   0.00  2.82  6.96  -5.46
74   47.51  2025-12-15  50.17  47.51   0.00  1.88  5.26  -4.89
75   46.11  2025-12-16  50.17  46.11   0.00  1.25  3.93  -4.10
76   47.10  2025-12-17  50.17  46.11  24.38  8.96  5.61  15.68
77   48.93  2025-12-18  50.17  46.11  69.46 29.13 13.45  60.49
78   48.11  2025-12-19  49.24  46.11  63.90 40.72 22.54  77.08
79   47.83  2025-12-22  49.24  46.11  54.95 45.46 30.18  76.03
80   47.08  2025-12-23  48.93  46.11  34.40 41.77 34.04  57.23
81   47.64  2025-12-24  48.93  46.11  54.26 45.93 38.01  61.79
82   48.00  2025-12-25  48.93  46.11  67.02 52.96 42.99  72.90
83   47.94  2025-12-26  48.93  46.11  64.89 56.94 47.64  75.54
84   48.39  2025-12-29  48.93  47.08  70.81 61.56 52.28  80.13
85   50.26  2025-12-30  50.26  47.08 100.00 74.38 59.65 103.83
86   48.12  2025-12-31  50.26  47.08  32.70 60.49 59.93  61.60
87   49.46  2026-01-05  50.26  47.08  74.84 65.27 61.71  72.40
88   49.29  2026-01-06  50.26  47.08  69.50 66.68 63.37  73.31
89   48.56  2026-01-07  50.26  47.64  35.11 56.16 60.96  46.55
90   49.74  2026-01-08  50.26  47.94  77.59 63.30 61.74  66.42
91   51.97  2026-01-09  51.97  47.94 100.00 75.53 66.34  93.92
92   51.28  2026-01-12  51.97  48.12  82.08 77.72 70.13  92.88
93   49.02  2026-01-13  51.97  48.12  23.38 59.60 66.62  45.56
94   48.90  2026-01-14  51.97  48.12  20.26 46.49 59.91  19.64
95   49.14  2026-01-15  51.97  48.56  17.01 36.66 52.16   5.66
96   48.28  2026-01-16  51.97  48.28   0.00 24.44 42.92 -12.52
97   48.42  2026-01-19  51.97  48.28   3.79 17.56 34.47 -16.26
98   47.22  2026-01-20  51.97  47.22   0.00 11.71 26.88 -18.64
99   47.31  2026-01-21  51.97  47.22   1.89  8.44 20.73 -16.16
100  47.45  2026-01-22  51.28  47.22   5.67  7.51 16.33 -10.11
101  47.69  2026-01-23  49.14  47.22  24.48 13.17 15.27   8.96
102  46.90  2026-01-26  49.14  46.90   0.00  8.78 13.11   0.12
103  47.14  2026-01-27  49.14  46.90  10.71  9.42 11.88   4.51
104  46.22  2026-01-28  48.42  46.22   0.00  6.28 10.01  -1.18
105  45.36  2026-01-29  48.42  45.36   0.00  4.19  8.07  -3.58
106  45.71  2026-01-30  47.69  45.36  15.02  7.80  7.98   7.44
107  44.01  2026-02-02  47.69  44.01   0.00  5.20  7.05   1.49
108  44.49  2026-02-03  47.69  44.01  13.04  7.81  7.31   8.83
109  44.77  2026-02-04  47.69  44.01  20.65 12.09  8.90  18.48
110  44.06  2026-02-05  47.14  44.01   1.60  8.59  8.80   8.18
111  44.08  2026-02-06  47.14  44.01   2.24  6.48  8.03   3.38
112  44.71  2026-02-09  46.22  44.01  31.67 14.87 10.31  24.01
113  44.94  2026-02-10  45.71  44.01  54.71 28.15 16.26  51.94
114  44.82  2026-02-11  45.71  44.01  47.65 34.65 22.39  59.18
115  44.38  2026-02-12  44.94  44.01  39.78 36.36 27.05  54.99
116  44.83  2026-02-13  44.94  44.06  87.50 53.41 35.83  88.56

In [ ]:
fig = px.line(history_data, x='eob', y=['k', 'd','j'],color_discrete_sequence=['white','yellow','purple'])  
fig.show()